[tool.poetry]
name = "openai"
version = "0.1.0"
description = ""
authors = ["Bejan Sadeghian"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
